package com.the_notorious_five.easyplate;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class FoodDatabase extends SQLiteOpenHelper {

    private static final String DB_NAME = "Dishes"; //the database name
    private static final int DB_VERSION = 1; //the version for which then the database can upgrade itself and so on by using different methods
    
    FoodDatabase(Context context){
        super(context, DB_NAME, null, DB_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db){
      createDatabase(db); //imediately create the database
    }

    
    // a method which makes it easier to insert all the dishes 
    private static void insertDish(SQLiteDatabase db ,String ingredients , String name, String description, int time , int resourceId) {
        ContentValues foodvalues = new ContentValues();
        foodvalues.put("INGREDIENTS" , ingredients);
        foodvalues.put("NAME", name);
        foodvalues.put("DESCRIPTION",description);
        foodvalues.put("TIME" , time);
        foodvalues.put("FAVOURITE" , 0);
        foodvalues.put("IMAGE_RESOURCE_ID", resourceId);
        db.insert("DISHES", null, foodvalues);
    }
    //the method which creates one database tables
    private void createDatabase(SQLiteDatabase db){
       //creating a table with the name dishes
       db.execSQL("CREATE TABLE DISHES (_id INTEGER PRIMARY KEY AUTOINCREMENT, INGREDIENTS TEXT, NAME TEXT , DESCRIPTION TEXT," +
               "TIME INTEGER ,FAVOURITE INTEGER , IMAGE_RESOURCE_ID INTEGER);");
       
       //inserting all the dishes
        insertDish(db, "2 tablespoons butter, divided\n1 slice bread\n1 egg", "Sunshine Toast", "Melt 1 tablespoon butter in a small skillet over medium heat.\n\nUsing a glass or cookie cutter, create a hole in the middle of the bread, removing the center so it is perfectly circular. Butter the bread lightly on both sides and lightly fry it on one side, and then turn it over. Crack the egg into the hole in the middle of the bread and fry quickly. Be careful that the bread does not burn. Serve warm.", 15, R.drawable.sunshinetoast);
        insertDish(db, "Boneless skinless chicken breast, thawed\nLemon, juice of\nTablespoon melted butter", "Solo Baked Chicken Breast", "Place a Cast Iron Frying Pan into an oven and preheat at 350 degrees for 10 minutes.\n\nDuring this time, IF the chicken breast is frozen, it can thawed in a microwave at power 3 for 7 minutes.\n\nPlace the thawed chicken breast into a shallow dish and add the juice of 1 lemon, coating both sides.\n\nLet sit for at least 5 minutes.\n\nCover both sides with pepper, and then coat the chicken breast with the butter, using a brush.\n\nPlace the chicken into the Cast Iron Pan and bake for 35 minutes.\n\nTo get an even browning, turn the chicken over half way through the baking time.\n\nNote:If a baking potato is punctured, microwaved on high for 3 minutes, and then coated with olive oil, it will be done in the same 35 minutes in the oven.", 45, R.drawable.chickenbreastsolo);
        insertDish(db, "1/4 cup butter, melted\n1 teaspoon salt\n4 skinless, boneless chicken breast halves", "Baked Chicken Breasts", "Preheat oven to 350 degrees F (175 degrees C). Lightly butter a baking dish.\n\nStir 1/4 cup melted butter and salt together in a bowl.\n\nArrange chicken in the baking dish. Brush butter mixture onto the chicken until thoroughly coated, pouring any extra over the chicken.\n\nBake in the preheated oven until no longer pink in the center and the juices run clear, about 30 to 45 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).", 40, R.drawable.chickenbreastsimple);
        insertDish(db, "2 cups long grain rice, washed\n1 teaspoon salt\n12 cups cold water\n2 potatoes, peeled and very thinly sliced\n1/2 cup melted butter", "Persian Rice", "Bring the water to a boil in a large pot, add the salt, and then boil the washed rice for ten minutes; drain and reserve.\n\nDip the potato slices in the melted butter and use them to line the bottom AND sides of the same pot you just boiled the rice in.\n\nPour any leftover butter in the bottom of the pot.\n\nNow, very carefully (don't move the potatoes), place the partially cooked rice into the potato-lined pot.\n\nCover the pot with a teatowel and then its lid and place over medium-low heat; this steams the rice and cooks and browns the potatoes.\n\nThis will take about 1/2 hour, but carefully check the rice for doneness and the potatoes for browning after about 20 minutes.\n\nWhen the rice and potatoes are done (potatoes will be browned and crispy), remove from heat and remove lid and teatowel.\n\nPlace a large platter over top of pot and very carefully invert the pot.\n\nThe whole thing should slide out; if some potatoes come away, put them back where they belong.\n\nI was told the crust is called the\"tadiq\" and it is the part the family members all fight over.\n\nI admit that, when I tried to make this dish, it all fell apart; it was tasty though.", 70, R.drawable.persianrice);
        insertDish(db, "15 (about 2.5kg) medium coliban potatoes, peeled, halved\n2 tablespoons olive oil\n50g butter, melted\nSea salt flakes, to serve", "Crispy Roast Potatoes", "Place the potato in a large saucepan of cold water. Bring to the boil over high heat. Simmer for 5 minutes or until slightly tender. Drain. Place, in a single layer, on a tray lined with paper towel. Set aside for 30 minutes to cool.\n\nPreheat oven to 180°C. Brush 2 large baking trays with a little oil. Combine the butter and remaining oil in a small bowl.\n\nUse a fork to scrape the curved side of the potato lengthways. Place, in a single layer, cut-side down, on the prepared trays. Brush with butter mixture. Roast in oven, brushing with the butter mixture once, for 50 minutes or until golden brown. Sprinkle with sea salt to serve.", 55, R.drawable.crispyroastpotatoes);
        insertDish(db, "1 pound sirloin steak (without much gristle) or pre-cut beef tips\nKosher salt and fresh ground black pepper\nButter", "Steak Bites", "Trim off the excess fat from the meat, and then cut strips less than 1-inch wide. Rotate the meat and cut into small bite-size pieces. If you see any more large chunks of fat, gristle or long silvery membrane, cut them off.\n\nSprinkle generously with kosher salt and freshly ground pepper. Toss the meat around a bit to thoroughly coat with the seasonings.\n\nNext, turn on your ventilation fan-you'll need it! Heat the skillet over medium-high to high heat. As the pan heats, add about 2 tablespoons butter to the skillet. Allow the butter to melt, and then get very brown, before you add the meat.\n\nPlace some of the meat in the pan in a single layer. It should sizzle loudly when it hits the pan - if it doesn't, the pan isn't hot enough. Don't stir or disrupt the meat for 30 to 45 seconds. You want it to sizzle and brown on one side. Scoop as many steak bites as you can with your spatula and flip them over. Repeat until all the meat is turned. Cook for an additional 30 to 45 seconds-just long enough to sear the outside of the meat but NOT cook the inside.\n\nRemove the meat to a clean plate. Add a little more butter to the pan and repeat the cooking process with the next batch just as before. Lastly, when all the meat is nicely browned and removed to the plate, pour all that browned/blackened butter all over the meat. And enjoy!", 25, R.drawable.beefsteaks);
        insertDish(db, "4 gold potatoes, sliced 1/4 inch thick\n4 tablespoons butter\n", "Easy Fried Potatoes", "Put the butter in a pan (I use a stick free, the butter is for taste) and melt.\n\nAdd potatoes, and turn over every few minutes until brown. Not all need to be brown, but make sure they are cooked through. Usually takes about 15 minutes.\n\nAdd salt and pepper sometime during frying time, to taste.", 20, R.drawable.easyfriedpotatoes);
        insertDish(db, "2 large eggs\n2 slices white bread\n1 teaspoon butter", "Scrambled Egg Sandwich", "Scramble 2 large eggs at medium heat.\n\nSpread 1 teaspoon butter on 2 white bread slices.\n\nPlace cooked eggs inside 2 white bread slices.\n\nPlace bread on medium heat for 1 minute each side.\n\nTurn off heat and enjoy!", 10, R.drawable.scrambledeggs);
        insertDish(db, "5 russet potatoes, peeled\n1/4 cup butter, divided\n1/2 large onion, diced\n8 eggs\n5 slices American cheese", "Potatoes, Eggs, and Cheese", "Place potatoes into a large pot and cover with salted water; bring to a boil. Reduce heat to medium-low and simmer until tender, about 20 minutes. Drain. Slice potatoes when cool enough to handle.\n\nMelt 2 tablespoons butter in a large skillet over medium heat; cook and stir onion in hot butter until slightly browned, about 10 minutes. Melt remaining 2 tablespoons butter in skillet; add sliced potatoes. Continue cooking until potatoes begin to brown, about 10 more minutes; stir often.\n\nBeat eggs in a bowl; pour beaten eggs over potatoes and let cook until egg begins to firm on the bottom, about 5 minutes. Carefully work a spatula underneath the eggs and potatoes and flip. Cook until eggs are firm and set throughout, 3 to 5 more minutes. Season with salt and black pepper.\n\nLay American cheese slices over egg-potato mixture and let melt before serving.", 50, R.drawable.eggspotatoescheese);
        insertDish(db, "1 pound spaghetti\n3/4 cup milk, plus more if needed\n1 egg\n2 tablespoons butter\n2/3 cup finely grated Pecorino Romano cheese, plus more to pass at the table", "Spaghetti with Butter, Egg and Cheese", "Cook the spaghetti in a large pot of generously salted water.\n\nWhile the spaghetti cooks, whisk together the milk and egg in a small bowl.\n\nOnce the pasta is cooked al dente, drain.\n\nPut the drained pasta back into the cooking pot. Turn the heat to low, add the milk/egg mixture and butter, and stir just until the milk thickens and coats the noodles, a minute or so.\n\nRemove from heat. Add the cheese and stir again. Taste and add salt and pepper to taste. If the pasta gets too sticky, thin it with a little more milk.\n\nServe immediately with more Pecorino Romano at the table", 30, R.drawable.spaghetticheeseandeggs);
        insertDish(db,"Sauce\nSausage\nCheese\nCream","Sausage Lasagne","Boil lasagne leaves in water with 1 tablespoon of  defrost sausages, fry (optional) till brown and slice.Add slices sausages to pasta sauce. Pour some of the mixture in a casserole dish to form a layer.Top with lasagne leaves with ends overlapping.Sprinkle mozzarella and parmesan. Add dollops or ricotta or heavy cream.Repeat for as many layers as desired.Top with mozzarella cheese and bake till cheese is slightly brown.",40 ,R.drawable.sausage_lasagne);
        insertDish(db,"Eggs\nMilk\nBread","French Toast","Mix eggs and milk well in a bowl. Dip the bread in the mixture.Heat oil. Deep fry the bread .Serve with tomato sauce! ( a really delicious recipe for those working with very less time in hand )",20 ,R.drawable.french_toast);
        insertDish(db,"Onion\nButter\nRice\nTomatoes\nChicken", "Oven-baked rissoto", "Heat oven to 200C/fan 180C/gas 6. Fry the bacon pieces in an ovenproof pan or casserole dish for 3-5 mins until golden and crisp. Stir in the onion and butter and cook for 3-4 mins until soft. Tip in the rice and mix well until coated. Pour over the wine if using and cook for 2 mins until absorbed.Add the cherry tomatoes and the hot stock, then give the rice a quick stir. Cover with a tightly fitting lid and bake for 18 mins until just cooked. Stir through most of the Parmesan and serve sprinkled with the remainder.", 35, R.drawable.baked_rissoto);
        insertDish(db,"Chicken\nMilk\nHerbs\nNoodles","Easy Noodles","Firstly, get the kettle on. Tip the stock, coconut milk, Thai curry paste, turmeric and chicken into a big microwaveable bowl. Cover with cling film, pierce it a few times and microwave on High for 5 mins. Remove the cling film, give it a stir and cook for a further 5 mins until the chicken is cooked.Meanwhile, tip the noodles into another large bowl. Pour boiling water over, leave to soak for 4 mins, then drain.Add the stir-fry mix and noodles to the chicken, ladle into deep bowls and serve with spoons and forks.",20,R.drawable.easy_noodles);
        insertDish(db,"Water\nChicken\nOnion\nCarrots\nPasta\nHerbs","Noodle soup","Combine 2 cups water and chicken broth in a microwave-safe dish, and microwave at HIGH for 5 minutes.While broth mixture heats, heat a large saucepan over medium-high heat. Add oil to pan; swirl to coat. Add onion, celery, salt, pepper, and carrot; sauté 3 minutes or until almost tender, stirring frequently. Add hot broth mixture and pasta; bring to a boil. Cook 7 minutes or until pasta is almost al dente. Stir in chicken; cook 1 minute or until thoroughly heated. Stir in parsley.",20,R.drawable.noodle_soup);
        insertDish(db,"Tomatoes\nWater\nPatato\nGarlic\nOil\nPepper","Tomato Soup","Peel and chop onion and garlic. Heat oil and fry onion and garlic until soft. Peel and chop the potato. Add water to pan, add potato and bring to boil. Once boiling, add tinned tomato, tomato puree, stir and simmer until potato is cooked. Add the chopped basil leaving some for garnish. Blend the mixture and season to taste) garnish with basil and serve with fresh bread.",35,R.drawable.tomato_soup);
        insertDish(db, "2 cups long-grain rice\n3 cups water", "Steamed White Rice","Put the rice in a 3 quart pot or saucepan with a tight fitting lid (don't put the lid on yet!) and pour in the water.\nBring to a boil, and cook until the surface looks \"cratery\" (like the surface of hot lava or something).\nReduce heat to low, cover, and cook for about ten minutes, till the water is gone.\nLet rice stand for a minute or two, then remove the lid, fluff the rice, and serve!", 17 , R.drawable.steamed_white_rice);
        insertDish(db, "2tbsp olive oil\n2 onions, peeled and chopped\n1 carrot, peeled and diced finely\n1 garlic clove, peeled and crushed\n450g fresh ripe tomatoes, halved\n1 litre vegetable stock\n1tsp sugar", "Tomato Soup ( 2nd Version)" , "Heat the oil in a large saucepan and add the onions, carrot and garlic. Cover and cook for 10 mins until soft.\nScore the bottom of the tomatoes with a sharp knife and place in boiling water for 2 mins.Transfer to a bowl of cold water and then remove the skins.\nChop tomatoes and push through a sieve into the pan, to remove the pips.Add the sugar, salt and pepper. Stir and cook for another 5 mins.Add the stock, bring to the boil and simmer for 10 mins. Liquidise until smooth.",55 , R.drawable.tomato_soup2);
        insertDish(db, "1 smoked sausage, sliced\n2 carrots, peeled and diced\n1 jar of tomato and basil sauce\n415g can of baked beans\n300ml water" , "Smoked sausage and bean casserole","Heat a splash of oil in a large pan and fry the carrots for 5 mins.\nStir in the tomato sauce and water. Bring to the boil, cover and then simmer for 15 mins.\nAdd the sausage and baked beans and cook for a further 10-15 mins until the carrots are tender.\n" , 40 ,R.drawable.smoked_sausage_and_bean_casserole);
        insertDish(db, "8 oz cheddar cheese\n1 tablespoon cornstarch\n¾ cup milk\n2 packages ramen noodles", "Ram n’ Cheese", "Grate cheddar cheese and add with cornstarch into a small bowl.\nCombine with milk in a medium saucepan and cook on medium to low heat until consistent.\nKeep warm until serving.In a separate pan boil ramen noodles.\nSet aside the included flavor packets.Once boiling, drain the noodles and combine with cheese.", 25, R.drawable.ram_n_cheese);
        insertDish(db, "1 tbsp of Low fat soft cheese\nCucumber slices\nTwo pieces of bread", "Refreshingly low-fat cucumber sandwich","Spread a good dollop of soft cheese onto both pieces of bread.\nArrange the cucumber slices so they are evenly distributed. Generally most sandwiches only need nine slices in a 3×3 arrangement.\n*Optional* sprinkle a little pepper over the cucumber to give it a nice peppery bite.\nClose the sandwich and slice as desired.\n*Optional* remove the crusts and cut into rectangles for the perfect afternoon tea treat.\nTuck in and enjoy!\n", 15 ,R.drawable.refreshingly_low_fat_cucumber_sandwich );
        insertDish(db, "Frozen fries\nChicken\nEnchilada sauce\nCheese\nBacon" , "Chicken Enchilada Curly Fries" , "Cook your fries and bacon per pack instructions.\nMeanwhile, dice the chicken or turkey into bite size pieces. Heat the chicken in a little oil in a frying pan. Season to taste.\nOnce chicken is lightly golden, add enchilada cooking sauce and mix well. Allow to simmer for 10 minutes.\nPlace the cooked chips in a bowl to serve. Top with grated cheese.\nAdd on spoonfuls of chicken enchilada mix.\nAdd more cheese and finish with chopped up bacon.\nMicrowave or place in the oven at 200 degrees until cheese has melted nicely." , 50 , R.drawable.chicken_enchilada_curly_fries);
        insertDish(db, "Rice\nUnsalted Butter\nWater\nSalt", "Basmati Rice", "Rinse rice in several changes of cold water until water runs clear. Drain well in a fine-mesh sieve. Melt butter in a 4-quart heavy pot over moderate heat, then add rice and cook, stirring, 2 minutes. Stir in water and salt and bring to a boil over high heat. Reduce heat to low and cook, covered, until rice is tender and liquid is absorbed, about 20 minutes. Remove from heat. Let stand, covered and undisturbed, 5 minutes. Fluff rice gently with a fork ( for 6 servings cups basmati rice (14 oz),2 tablespoons unsalted butter , 3 1/3 cups water, 1 teaspoon salt )", 40 , R.drawable.basmati_rice);
        insertDish(db, "Onion\nBacon\nRice\nStock\nPea","Easy Risoto with Bacon","Finely chop the onion. \nHeat 2 tablespoons of olive oil and a knob of butter in a pan, add the onions and fry until lightly browned (about 7 minutes)\n. Add the bacon and fry for a further 5 minutes, until it starts to crisp. \nAdd the rice and stock, and bring to the boil. Stir well, then reduce the heat and cook, covered, for 15-20 minutes until the rice is almost tender.\n Stir in the peas, add a little salt and pepper and cook for a further 3 minutes, until the peas are cooked. Serve sprinkled with freshly grated parmesan and freshly ground black pepper.",40, R.drawable.easy_risoto_with_bacon);
        insertDish(db, "Orecchiette\nOliveOil\nGarlic\nGreenOlives\nPassata","Pasta and green olives","Cook the pasta according to the packet instructions in a large pan of boiling salted water.\nPeel, slice and fry the garlic for a few minutes in the oil until softened.\nStone and chop the green olives, reserving the brine. \n Add the olives to the pan, season, stir and cook for 2 minutes. Stir in the passata and the brine, and cook for 5 minutes.\nReserving the cooking water, drain and add the pasta to the sauce. \nServe immediately.  \n (250 g orecchiette , 3 tablespoons olive oil , 2 cloves of garlic , 1 x 150 g jar of green olives (stones in),8 tablespoons passata- for 2 people )",15,R.drawable.pasta_and_green_olives);
        insertDish(db, "Sphaghetti\nBlack Olives\nFresh Basil\n Garlic\nOlive Oil\nHard Cheese","Salsa Spaghetti", "Let the tomatoes ripen naturally out of the fridge. \nCook the spaghetti in a pan of boiling salted water for 8 to 10 minutes or until al dente, which means that it should be soft enough to eat, but still have a bit of bite and firmness to it. \nOn a large chopping board, chop the tomatoes. \n Bash the olives and tear out the stones, then add the olives to the pile of tomatoes. \n Pick the basil leaves, reserving the smaller ones for later and throw the rest onto the pile. Peel, chop and add the garlic to the pile, then run your knife back and forth through all of the ingredients, chopping and mixing as you go, until you get a rough-looking salsa. \n Add a good couple of lugs of oil and a pinch of sea salt and black pepper, and keep chopping and mixing until well combined.\nScoop out and reserve a cupful of the pasta cooking water, then drain the spaghetti in a colander. \nPop the spaghetti in a large bowl, scrape in the salsa dressing, adding a splash of the reserved cooking water, if needed, to make a lovely loose sauce. \nSprinkle over the reserved baby basil leaves and add a grating of hard Italian cheese before serving. (320 g dried spaghetti, 600 g mixed ripe tomatoes , 12 black olives (stone in), 1 bunch of fresh basil,clove of garlic,extra virgin olive oil, 2 tablespoons red wine vinegar ,20 g hard Italian cheese- for 4 people)",15,R.drawable.salsa_spaghetti);
        insertDish(db,  "Basil \nOnion \nGarlic \nTomatoes \nOlive Oil\nSalt\nPepper\nSpaghetti\nCheese","Classic Tomato Spaghetti"," Pick the basil leaves onto a chopping board (reserving a few baby leaves to garnish), then roughly chop the remaining leaves and finely chop the stalks.\nPeel and finely slice the onion and garlic. \n If using fresh, cut the tomatoes in half, then roughly chop them or carefully open the tins of tomatoes.\nPut a saucepan on a medium heat and add 1 tablespoon of olive oil and the onion, then cook for around 7 minutes, or until soft and lightly golden.\nStir in the garlic and basil stalks for a few minutes, then add the fresh or tinned tomatoes.\n Season with a tiny pinch of salt and pepper, then continue cooking for around 15 minutes, stirring occasionally.Stir in the chopped basil leaves, then reduce to low and leave to tick away. Meanwhile…\n Carefully fill a large pot three-quarters of the way up with boiling water, add a tiny pinch of salt and bring back to the boil.\n Add the spaghetti and cook according to packet instructions – you want to cook your pasta until it is al dente. This translates as ‘to the tooth’ and means that it should be soft enough to eat, but still have a bit of a bite and firmness to it. Use the timings on the packet instructions as a guide, but try some just before the time is up to make sure it’s perfectly cooked.\n Once the pasta is done, ladle out and reserve a cup of the cooking water and keep it to one side, then drain in a colander over the sink and tip the spaghetti back into the pot.Stir the spaghetti into the sauce, adding a splash of the pasta water to loosen, if needed.Serve with the reserved basil leaves sprinkled over the top and use a microplane to finely grate the Parmesan cheese, then sprinkle over.\n Tips: It’s important to season the cooking water so that the pasta can absorb it as it cooks. Once you’ve made this a few times you can add other simple ingredients, such as baby spinach, chopped rocket leaves, or fresh or frozen peas, to your basic tomato sauce to completely transform it.\n Reserving and adding a splash of pasta cooking water to your sauce helps to loosen it, if it’s a bit thick.( a bunch of fresh basil, 1 medium onion ,2 cloves of garlic, 1 kg ripe tomatoes , or 2 x 400g tins of chopped tomatoes, olive oil,  salt, freshly ground black pepper, 500 g dried spaghetti, 15 g cheese – for 8 people)",75,R.drawable.classic_tomato_spaghetti );
        insertDish(db, "Water\nChicken Broth \nLemon Juice\nButter( or Margarine) \nRice \nLemon \nLemon Pepper Seasoning","Lemon Rice", "Combine all ingredients EXCEPT lemon pepper in saucepan. \n Bring to a boil, then reduce heat. Cover pot and allow to simmer slowly for 20 minutes, or until liquid is absorbed. Sprinkle with lemon pepper before serving. \n (1 cup water, 1 cup chicken Broth , 2 tablespoons butter, 1 cup uncooked rice, ¼ teaspoon dried basil, 1/8-1/4 gratedlemon, ¼ teaspoons lemon pepper seasoning- for 4 people)",25,R.drawable.lemon_rice);
        insertDish(db, "Butter \nEggs( beaten)\nButter ( margarine)\nOnion\nRice\nSoy sauce ","Fried Rice", " Melt 1 tablespoon butter in skillet or wok. \n Scramble eggs in butter, breaking up the cooked eggs into small pieces. Set aside. Melt 1 tablespoon butter in skillet or wok. \n Saute onions and/or green peppers in butter for 3 minutes. Combine eggs, onions, rice, and meat. \n Stir in soy sauce until color of rice is uniform. Stir in peas. \n Heat only until warm.( Butter or 1 tablespoon margarine, 2 eggs( beaten) , 1tablespoon butter , 1⁄4cup chopped onion, 2 cups rice, prepared and cooled,), 1⁄4cup soy sauce - for 4 people)", 25, R.drawable.fried_rice);
        insertDish(db, "Rice \nGarlic \nVegetable oil\nOnion (chopped)\nTomato sauce\nChicken broth\nCumin","Spanish Rice"," Brown rice in oil using a 4 quart sauce pan. \n Add chopped onion, minced garlic and cumin. Add tomato sauce and chicken broth Bring to a boil-- reduce heat to low-- cover and cook for 15 mins. \n ( 1 1⁄2cups uncooked white rice ,2cloves garlic (minced), 2tablespoons vegetable oil , 1small onion (chopped), 4ounces cans tomato sauce, 2 1⁄2cups chicken broth, 1teaspoon cumin- for 4-6 people",30, R.drawable.spanish_rice);
        insertDish(db, "Ground lamb \nGarlic \nOregano (crushed)\nOnion powder \nSalt \nPepper","Gyro Meat", "Combine ingredients in a bowl, and shape into 1/2 inch thick patties. \n Broil 8-10 minutes until no longer pink. \n Slice thinly and serve with pita bread, sliced tomatoes, thinly sliced onion, cucumber yogurt sauce. \n ( 1lb lean ground lamb , 2cloves garlic (crushed), 1 1⁄2teaspoons dried oregano (crushed), 1teaspoon onion powder, 1teaspoon salt,3⁄4teaspoon pepper- for 6-8 people)",20, R.drawable.gyro_meat);
        insertDish(db,  "Olive oil\nEggs\nKosher Salt\nGarlic Powder\nOnion Powder\nRed Pepper\nBlack Pepper\nCheddar\nOnion","Egg Muffins", "Preheat oven to 375 degrees F. Line a rimmed baking sheet with foil. \n Place 14 silicone muffin cups on the foil and spray the cups with nonstick spray. It's important to use silicone cups in this recipe – the eggs tend to stick to a metal muffin tin and even to paper liners.\n In a large bowl, whisk together the eggs, yogurt, salt, garlic powder, onion powder, red pepper flakes, black pepper and coconut flour.With a fork, mix in the cheese and onions.\n Fill the prepared muffin cups, almost to the edge.Bake 30-35 minutes, or until muffins are set, puffed and lightly browned, and a toothpick inserted in center comes out clean.\n Allow the egg muffins to cool for 5 minutes until easier to handle, then remove to a wire rack.", 50, R.drawable.egg_muffins);
        insertDish(db, "Olive Oil\nPeas\nGarlic\nSesame Oil\nSoy Sauce\nKosher Salt\nBlack Pepper\nSesame Seeds", "Sauteed Sugar Snap Peas","Heat the olive oil in a large skillet over medium-high heat. \nAdd the peas and stir-fry until tender-crisp, about 3 minutes.\nAdd the garlic and cook, stirring, one more minute.\nRemove from heat and stir in the sesame oil, soy sauce, salt and pepper. Sprinkle with sesame seeds and serve.( 1 tablespoon olive oil, 1 lb. sugar snap peas, end and strings removed, 1 tablespoon minced garlic, 1 tablespoon sesame oil, 1 tablespoon light soy sauce, ½ teaspoon kosher salt, ¼ teaspoon black pepper, 1 teaspoon sesame seeds- for 4 people)", 10, R.drawable.sauteed_sugar_snap_peas );
        insertDish(db, "Patatoes\nOnion\nOlive Oil\nKosher Salt\nBlack Pepper\nGarlic Powder\nPaprika","Roasted Potatoes and Onions","Preheat oven to 425 degrees F.\nIn a large bowl, add the potatoes, onion slices, olive oil, salt, pepper, garlic powder, paprika and (if using) cumin. Use your clean hands to mix well.\nTransfer the mixture to a 13 X 9-inch baking dish, or an equivalent casserole dish.\nRoast until potatoes are tender and onions are caramelized, about 40 minutes, gently stirring midway through roasting.\n (1 lb. small potatoes, unpeeled, washed and dried, halved ,1 large onion, thickly sliced, ¼ cup olive oil, 1 teaspoon kosher salt, ¼ teaspoon black pepper, ½ teaspoon garlic powder,½ teaspoon paprika –for 4 people)", 55, R.drawable.roasted_potatoes_and_onions);
        insertDish(db, "Olive Oil\nBroccoli\nEggs\nYogurt\nKosher Salt\nPepper\nGarlic\nCheese" ,"Crustless Quiche", "Preheat oven to 400 degrees F. Spray a 9-inch pie dish with nonstick spray.\nBring a medium pot of water to a boil. Add the broccoli. Cook 1 minute, just to defrost. Drain well.\nIn a large bowl, whisk together the eggs, yogurt, salt, black pepper and garlic. Stir in the broccoli and the cheese.\nTransfer the broccoli mixture to the prepared pie dish. Bake until golden-brown and a knife inserted in center comes out clean, 30-35 minutes. (Olive oil spray (make your own using a spray bottle), 1 (10 oz) package frozen chopped broccoli, 6 large eggs, ½ cup plain Greek yogurt, 1 teaspoon kosher salt, ¼ teaspoon ground pepper, 1 tablespoon minced garlic,¾ cup (3 oz) shredded sharp cheddar cheese- for 4 people)",50,R.drawable.crustless_quiche);
        insertDish(db,  "Mozzarella Sticks\nBacon","Bacon Wrapped Mozzarella Sticks","Remove the cheese wrappers. Place the cheese sticks on a wax-paper-lined tray and freeze for at least four hours. I froze them overnight, the night before I made them.\nPreheat your oven to 400 degrees F. Line a large baking sheet with parchment paper.\nPartially cook the bacon: place two paper towels on a microwave-safe plate. Place four slices of bacon on top. Cover the bacon with two more paper towels (to prevent splatters). \nMicrowave for 2 minutes. Repeat with the remaining slices.\nThis renders some of the fat and will help the bacon crisp up faster, preventing the cheese from melting away during prolonged baking.\nWrap each half mozzarella stick with a slice of bacon, securing with a toothpick.\nPlace the wrapped cheese sticks on the prepared baking sheet. Bake until cheese just starts to melt, 5-7 minutes. Serve immediately. (6 part-skim mozzarella sticks, cut in half crosswise, 12 slices uncured bacon- for 4 people)",15,R.drawable.bacon_wrapped_mozzarella_sticks);
        insertDish(db, "Seafood\nOlive Oil\nGarlic\nPaprika\nKosher Salt\nRed Pepper\nLemon\nParsley ","Seafood Sauce","Rinse the seafood, one piece at a time, in cool water to defrost and get rid of icy parts. Place on a clean kitchen towel to dry. This is the only tedious part of the recipe and is well worth it, otherwise the pieces won’t cook as well and will release too much water into the sauce.\nPlace the defrosted seafood in a large bowl. Add the olive oil, garlic, paprika, salt and red pepper flakes. Use your clean hands to coat the seafood with the oil and seasonings.\nHeat a very large skillet over medium-high heat, about 2 minutes. Add the seasoned seafood. Stir-fry 3-5 minutes, just until opaque and not a second longer.\nTransfer to a serving platter, spooning the sauce on top. Squeeze lemon juice on top and garnish with chopped parsley. Serve immediately.\n2 lb. frozen mixed seafood (my mix had shrimp, calamari rings, and bay scallops), 4 tablespoons olive oil, 1 tablespoon minced garlic, 1 tablespoon sweet paprika, 1 teaspoon kosher salt, ½ teaspoon red pepper flakes, ½ lemon, 2 tablespoons chopped parsley-for 4 people",20, R.drawable.seafood_sauce);
        insertDish(db,"Eggs\nVanilla\nMilk\nKosher Salt\nFlour\nBaking Soda\n,Butter\n,Chocolate Chips","Glutten Free Pancakes","Preheat oven to 200 degrees F. Prepare a large baking sheet - you'll use that to keep the cooked pancakes warm while you cook more.\nIn a large bowl, whisk together the eggs, vanilla, milk and salt.\nWhisk in the almond flour, then the baking soda. Whisk until smooth. Since there's no gluten in this pancake batter, you don't need to worry about over mixing.\nHeat a double-burner griddle over medium heat, about 4 minutes. Add 1 tablespoon butter and brush to coat.\nLadle the batter onto the griddle, measuring 2 tablespoons per pancake. Cook until bottom is golden and set, about 3 minutes. Scatter a few chocolate chip on the uncooked top of each pancake.\nTurn the pancakes and cook until golden and set on the second side, 2-3 more minutes.\nTransfer the cooked pancakes to the baking sheet you've prepared and place in the oven to keep warm.\nBrush the griddle with 1 more tablespoon of butter and cook the remaining pancakes. Serve with warm maple syrup or with honey.\n( 3 large eggs, 2 tablespoons vanilla extract, ½ cup whole milk, ¼ teaspoon kosher salt, 2 cups (8 oz) almond flour, 1 teaspoon baking soda, 2 tablespoons butter for griddle, divided, ⅓ cup (40 grams) dark (70%) chocolate chips (optional)- for 18 pancakes)", 30, R.drawable.gluten_free_pancakes );
        insertDish(db, "Vegetables\nWater\nCider Vinegar\nKosher Salt\nPeppercorns\nCoriander\nBay Leaf","Quick Pickles","Place the vegetables in a 20-ounce glass jar.\nCombine the remaining ingredients in a small saucepan. Bring to a boil over high heat.\nPour the mixture over the vegetables. Cover, and refrigerate for 6 hours or overnight.\nThese quick pickles keep in the fridge for up to 2 weeks.\n(2 cups sturdy vegetables - used 1 cup sliced carrots and 1 cup green beans, 1 cup water, 1 cup apple cider vinegar, 2 tablespoons kosher salt, 1 tablespoon whole peppercorns, 1 tablespoon whole coriander, 1 bay leaf- for 4 servings)",480,R.drawable.quick_pickles);
        insertDish(db, "Pork\nKosher Salt\nBlack Pepper\nOnion Powder\nGarlic Powder\nPaprika\nDried Thyme\nCoriander\nGround Cumin","Pork Meatballs","Preheat oven to 400 degrees F. Line a large baking sheet with parchment paper.\nIn a large bowl, use your clean hands to mix together all the ingredients. Shape into 32 meatballs, each weighing about 1 oz (30 grams).\nArrange the meatballs in a single layer on the prepared baking sheet. Bake until browned and cooked through, about 15 minutes. (2 lb. ground pork, 2 teaspoons coarse kosher salt, ½ teaspoon black pepper, 2 teaspoons onion powder, 2 teaspoons garlic powder, 2 teaspoons sweet paprika, 1 teaspoons dried thyme, 1 teaspoon coriander, 1 teaspoon ground cumin- for 8 servings)", 25 , R.drawable.pork_meatballs);
        insertDish(db,"Olive Oil\nEggs\nWater\nGarlic Powder\nOnion Powder\nOregano\nCoconut Flour\nParmesan Cheese\nMarinara Sauce\nMozzarella","Coconut Flour Pizza Crust","Preheat oven to 400 degrees F.\nLine two pizza pans with parchment paper and spray the paper with olive oil. You can also make these pizzas side by side on a single, large baking sheet. \nIn a large bowl, whisk the eggs with the water, garlic powder, onion powder and dried oregano.\nMeasure out the coconut flour, breaking up any lumps with your hands. Stir the coconut flour into the egg mixture, mixing until smooth.\nStir in the Parmesan cheese.\nAllow the mixture to rest and thicken for a couple of minutes. This will allow the coconut flour to soak up the liquid. \nUsing a rubber spatula, transfer half of the mixture onto each of the prepared pans. Use a spatula to spread it out evenly into an 8-inch circle.\nBake the pizzas until set and the edges are beginning to brown, about 15 minutes.\nThe crust will still be light at this point, and that's OK. \nRemove the pizzas from the oven and switch the oven to broil. Position the top oven rack 6 inches below flame.\nSpread each pizza with half the pizza sauce, sprinkle with half the shredded mozzarella, and add any other toppings you like (I used Applegate’s pepperoni).\nBroil each pizza until cheese is melted and crust is golden-brown, 2-3 minutes.(Olive oil spray for pans, 4 large eggs, 2 tablespoons water, 1 teaspoon garlic powder, 1 teaspoon onion powder, 1 teaspoon dried oregano, ¼ cup coconut flour, 6 tablespoons (1 oz) grated parmesan cheese, ½ cup marinara sauce (I like Rao’s), 1 cup (4 oz) shredded part-skim mozzarella- 2 pizzas)",30, R.drawable.coconut_flour_pizza_crust);
        insertDish(db, "Olive Oil\nSpaghetti Sauce\nMilk\nRice Pasta\nMozzarella","Pasta Bake","Preheat oven to 375 degrees F. Grease a 9 X 13-inch baking dish with olive oil.\nIn a large bowl, whisk together the pasta sauce and milk. Stir in the pasta and 1 ¾ cups of the cheese.\nCover the pan tightly with foil and bake 30 minutes. Uncover, stir, sprinkle with the remaining cheese, and bake 30 more minutes, until browned. Allow to rest 10 minutes before serving.\n( 2 teaspoon olive oil for the baking dish, 2 cups spaghetti sauce, 1cups whole milk, 1 (12oz) box brown rice pasta, 2 cups shredded mozzarella- for 8 people)",80, R.drawable.pasta_bake);
        insertDish(db, "Butter\nEggs\nHoney\nVanilla Extract\nFlour\nCocoa Powder\nKosher Salt\nBaking Soda","Almond Flour Chocolate Cake" ,"Preheat oven to 350 degrees F. Line a 9-inch glass pie plate with a circle of parchment paper. Grease the pan well.\nIn a large mixing bowl, whisk together the eggs, honey and vanilla extract.\nGradually whisk in the almond flour and cocoa powder.\nFinally, whisk in the salt and baking soda. Batter will be fairly thin.\nPour the batter into the prepared pan. Bake 30 minutes. Loosely cover with foil to prevent over-browning, then continue baking for 10 more minutes, until set and a toothpick inserted in center comes out clean.\nCool the cake on a cooling rack until it reaches room temperature, about 30 minutes, then slice and serve. Keep leftover covered in fridge for up to a week. (1 teaspoon melted butter for pan, 4 large eggs, ½ cup honey, 1 tablespoon vanilla extract, 1 cup blanched almond flour, ½ cup unsweetened cocoa powder, ½ teaspoon kosher salt, ½ teaspoon baking soda – for 8 servings)",80,R.drawable.almond_flour_chocolate_cake);
        insertDish(db, "Chicken Breast\nOlive Oil\nKosher Salt\nBlack Pepper\nGarlic Powder\nOnion powder\nOregano\nPaprika","Baked Chicken Breasts","Preheat oven to 450 degrees F. Line a baking dish with foil.\nSpray or brush both sides of each chicken breast with olive oil, and sprinkle with the seasonings.\nBake, uncovered, for 10 minutes, flip to the other side, lightly spray/brush again and bake for 8-10 more minutes, or until juices run clear when pierced with a fork (it's fine to make a small slit in the thickest part and see if it's done!).\nTransfer the baked chicken breasts to a platter. Loosely cover with foil and allow to rest 5 minutes before slicing and serving. (2 large boneless, skinless chicken breasts, olive oil cooking spray, or 2 teaspoons olive oil, ½ teaspoon kosher salt, ¼ teaspoon freshly ground black pepper, ¼ teaspoon garlic powder, ¼ teaspoon onion powder, ¼ teaspoon dried oregano, ¼ teaspoon paprika- for 2 servings)",30, R.drawable.baked_chicken_breasts);
        insertDish(db, "Spaghetti Squash\nButter\nKosher Salt\nGarlic Powder\nBlack Pepper\nParmesan Cheese","Butter Garlic Spaghetti Squash","Pierce the spaghetti squash all over with a fork. Place on a microwave-safe plate. \nMicrowave until fork-tender, 10-15 minutes, turning halfway through cooking.\nTransfer the cooked spaghetti squash to a cutting board. Allow to rest until cool enough to handle, about 10 minutes.\nUsing a sharp knife, cut the spaghetti squash open lengthwise. Use a spoon to remove the seeds and pulp from the middle and discard (or save the seeds and roast them).\nRake a fork back and forth over the spaghetti squash halves, to remove its flesh in strands.\nPlace the butter in a large saucepan. Heat over medium-high heat. When butter melts and starts to foam, add the spaghetti squash strands, salt, garlic powder and pepper. Cook, stirring, until the spaghetti squash strands are well-coated, 1-2 minutes.\nAdd the cheese, sprinkling it evenly on top. Continue cooking and stirring, just until well-incorporated, 1-2 more minutes. Serve immediately.(1 medium (3 lb.) spaghetti squash,4 tablespoons unsalted butter*, 1 teaspoon kosher salt, ½ teaspoon garlic powder, ¼ teaspoon black pepper, ½ cup grated Parmesan- for 4 people)",40 , R.drawable.butter_garlic_spaghetti_squash);
        insertDish(db, "Bananas\nVanilla\nCocoa Powder","Chocolate Banana Puding"," Place the banana slices on a wax-paper-lined baking sheet or platter. Freeze for 1 hour.\nPlace the partially frozen bananas in your food processor. Add the vanilla or almond extract. Process until very smooth, 1-2 minutes (depending on how powerful your food processor is), scraping the sides and bottom with a spatula as needed.\nAdd the cocoa powder.\nProcess until fluffy and creamy, about 1 more minute, scraping the sides with a spatula as needed. Serve immediately.( 6 (3.5 oz each) medium bananas, very ripe, thinly sliced, 1 teaspoon pure vanilla or almond extract, ¼ cup high-quality unsweetened cocoa powder- for 4 people)",70, R.drawable.chocolate_banana_puding);
        insertDish(db,  "Bananas\nCinnamon\nCoconut Oil","Fried Bananas","Slice the bananas and sprinkle with cinnamon.\nHeat a large skillet over medium heat, about 3 minutes.\nAdd the coconut oil and swirl to coat.\nAdd the banana slices in a single layer.\nCook until golden, 2-3 minutes on each side. (2 medium, firm bananas, ½ teaspoon ground cinnamon, 1 tablespoon extra virgin coconut oil- for 2 servings)",10 , R.drawable.fried_bananas);
        insertDish(db, "Plantain\nOlive Oil\nKosher Salt\nChili Powder\nGarlic Powder\nCumin\nCayenne Pepper","Baked Plantain Chips","Preheat oven to 400 degrees F. Line a cookie sheet with parchment paper.\nCut the ends of the plantain, then peel it with a paring knife (plantains do not peel as easily as bananas, hence the need to use a knife).\nSlice the plantain as thinly and uniformly as you can (use a mandoline if you have one). Most recipes tell you to slice them on the diagonal, but I like them round.\nIn a small bowl, toss the plantain slices with the olive oil and seasonings. Spread in a single layer on the prepared cookie sheet.\nBake 8-10 minutes per side, or until browned and crispy on both sides. Serve immediately – plantain chips lose their crispness after a few hours. (1 green plantain (6 oz), 1 tablespoon extra-virgin olive oil, ½ teaspoon kosher salt, ½ teaspoon chili powder, ¼ teaspoon garlic powder, ¼ teaspoon cumin,⅛ teaspoon cayenne pepper- for 2 servings)",30 , R.drawable.baked_plantain_chips);
        insertDish(db, "Chocolate\nCoconut Milk","Chocolate Pudding","In a medium pot, heat the chocolate and coconut milk over medium heat, stirring until chocolate is melted.\nTurn heat off and whisk the mixture with a hand whisk until very smooth.\nPour into five 4oz ramekins or dessert glasses, cover and refrigerate at least 2 hours before serving.( 3½ oz bittersweet (70%) chocolate, broken into pieces , 1 cup full-fat, unsweetened canned coconut milk-for 5 servings)",130,R.drawable.chocolate_pudding);
        insertDish(db, "Rice\nMilk\nMaple Syrup\nRaisins\nVanilla Extract\nCinnamon","Breakfast Rice","Place all the ingredients in a small saucepan.\nSimmer over medium heat, stirring frequently, about 5 minutes, until creamy and most milk has been absorbed.\n(1 cup cooked rice ,¼ cup whole milk, 1 tablespoon pure maple syrup,2 tablespoons raisins, ⅛ teaspoon pure vanilla extract, ⅛ teaspoon ground cinnamon- for 1 person)",10, R.drawable.breakfast_rice);
        insertDish(db, "Potatoes\nButter\nMilk\nHoney\nKosher Salt\nCinnamon","Mashed Sweet Potatoes","Pierce the sweet potato with a fork on both sides. Microwave on high, 3 minutes per side or until tender (they’re ready when the flesh is easily pierced with a fork). Let stand 5 minutes until cool enough to handle.\nMeanwhile, in a small saucepan over medium-low heat, heat the remaining ingredients, stirring, until warm but not hot. Don’t allow the mixture to boil.\nUse your fingers to peel the cooked sweet potato. Place it in a medium bowl. Mash well with a fork. Add the warm liquids gradually, whisking them in with a hand whisk. Keep whisking until very smooth, then serve.( 1 very large (13 oz) sweet potato, unpeeled, washed and dried, 2 tablespoons unsalted butter, 2 tablespoons whole milk, 1 tablespoon honey, ⅛ teaspoon kosher salt, ⅛ teaspoon cinnamon – for 3 servings)",16 , R.drawable.mashed_sweet_potatoes);
        insertDish(db, "Eggs\nMilk\nVanilla Extract\nSugar\nCinnamon\nButter\nTortillas","Tortilla French Toast","In a shallow dish, whisk together the egg, milk and vanilla.\nIn another shallow dish, mix together the sugar and cinnamon.\nHeat a double-burner griddle over medium heat, about 3 minutes. Add the butter, swirling or brushing to coat.\nDip each tortilla in the egg mixture, on both sides, until well-coated. Shake off the excess. Place on hot griddle.\nFry the tortillas about 2 minutes on each side, until puffed and golden-brown. Dredge in cinnamon sugar, fold in half and again in half, and serve.( 1 large egg, ¼ cup whole milk, 1 tablespoon pure vanilla extract, ¼ cup sugar, 1 teaspoon ground cinnamon, 1 tablespoon unsalted butter, 4 (6-inch) whole-wheat flour tortillas – for 4 servings)",10 ,R.drawable.tortilla_french_toast);
        insertDish(db,"Biscuits\nMilk\nButter","Easy Biscuit Cake","Grind both the biscuits like powder and empty in a large bowl.\nAdd milk to the mixture.Mix it well.Grease the moulds.\nAnd eno or baking powder to the batter.\nPut a stand in the cooker and put steel plate/dish on the stand.\nPour the batter in the moulds and keep it in the cooker for 12-15 mins.\n(note- don't put whistle ont top of cooker and water in the cooker)\nTake out the cake and put a toothpick in \nit and if the toothpick comes out clean,\n your delicious cake is ready!!!! ", 25, R.drawable.easy_biscuit_cake);
        insertDish(db,"Potatoes\nOnion\nLemon\nPepper\nSalt", "Patato Salad ","Boil potatoes until cooked and allow to cool.\nChop spring onions into small pieces and add to the potatoes in a large bowl.\nSqueeze a little lemon juice over the potatoes and spring onions.\nAdd mayonnaise and seasoning and mix well.Keep refridgerated.", 15,R.drawable.patato_salad);
        insertDish(db,"Sugar\nEggs\nFlour" , "Swiss Roll, " ,"Put eggs and sugar into a bowl.\n Whisk with electric whisk on full blast for 15-20 minuites.\nSprinkle on flour (and cocoa)\nFold in the flour/cocoa.Put in the oven\n (You need a baking tray that is lined with greaseproof paper) for 5 mins.\nFlip onto a wet teatowel.Add the jam with knife.\nRoll and push,eat the great creation. " , 40 , R.drawable.swiss_roll);
        insertDish(db,"Vanilla\nEggs\nMilk\nOil\nSugar\nFlour", "Cake in a cup " ,"Add dry ingredients into cup and mix well.Add egg, and mix thoroughly.\nPour in oil, vanilla, & milk and mix well.\nSet your cup in the microwave for 2 1/2 - 3 minuets. Watch carefully!\nRemove cup from microwave.Serve with chocolate syrup or whipped cream and enjoy!" ,15, R.drawable.cake_in_a_cup);
        insertDish(db,"Bread\nOnion\nSalt\nTomatoe\nCheese" ,"Paneer Sanwhich ","Heat the pan and pour some oil.\nPut some chopped onions and saute till golden brown.\nPut 1 tsp of chilly powder.Add a pinch of garam masala powder, a pinch of salt and some tomato sauce.\n It should be saucy!!! If not pour some water..then put the paneer and coriander leaves.\nSwitch off the gas.Take a bread and put this filling and keep another slice of bread.\nHeat a pan and fry this bread with breaking it and the filling should not get out.\n Heat with some butter or ghee." , 35, R.drawable.paneer_sanwhich);
        insertDish(db,"Swede\nCarrot\nTomatoes\nPepper\nOnion\nWater " ,"Swede, Carrot And Tomato Soup" ," Chop up the onion, swede and carrot.Put the onion in a saucepan for 3 minutes or until it starts browning\n(tip fry on a high heat and add a little water, saves money on oil and browns onions easily!)\nAdd the swede and carrot, cook these for another 3 minutes.\nAdd the tin of tomatoes, seasonings and water to the top,\n depending on how large the pan is.\nThen simply leave on a simmer for about 20 minutes to an hour depending on how much time you have.\nAdd more water if neededduring the cooking process.Blend the soup with a blender or stick blender.\nWater can still be added now if needed to thin the soup.\n(You can do the same process using less water to make a sauce for pasta or rice).\nENJOY!" , 45, R.drawable.swede_carrot_and_tomato_soup);
        insertDish(db,"Onions\nButter\nHerbs\nBread\nCheese " , "Simple Onion Soup" , "First thinly slice the onions. As you do this, melt the butter in a pot, and add the onion as you chop them. Stir the onions frequently and wait for them to become \"glassy\" as the butter soaks into them (you may need to add more butter here).once they are glassy, add enough stock to cover the onions (as well as any herbs/spices you may want). Then cook for about 10 minutes (while continuously stirring), or until all of the onion pieces are soft.optional:if you want, you can get a slice of bread, usually white slice pan, toast it, add some butter and place it on top of the soup in the serving bowl. You can then take a few slices of cheese (hard cheeses such as cheddar work best) and put them on the bread. Then microwave the whole soup and bread for a few seconds until the cheese melts.enjoy! Onions are cheap, and while butter can be expensive, you could use any kind of fat. It is a relatively quick and definitely delicious recipe!", 20 ,R.drawable.simple_onion_soup );
        insertDish(db,"Spinach\nOnions\nButter\nPepper\nMilk\nSalt", "Spinach Soup" , " Heat 1 tea spn butter. When it melts, add spinach and fry for 1-2mins. Add 1 cup water and cook till spinach leaves become tender. Grind them into a smooth puree using mixer/blender.Heat remaining butter and fry onions till they turn translucent. Now add spinach puree. Mix corn flour in milk or water and add this to the spinach mixture stirring continuously. Add salt and pepper. When it thickens to desired consistency, take off from heat.serve hot.", 15, R.drawable.spinach_soup);
        insertDish(db,"Oil\nOnions\nPatatoes\nTomatoes\nChicken\nCarrots\nGarlic ", " Easy Vegetable Soup " , "In a big saucepan on low to medium heat, add oil and saute the onion for a couple of minutes.\nAdd garlic, saute for a further minute.\nPut heat up to medium and add all the vegetables to the saucepan, saute for five minutes.\nAdd diced tomatoes and passata, stir through for a minute.\nAdd chicken stock and bring it to the boil.\nTurn down the heat and let it simmer on low to medium heat for 25-30 minutes\n - add salt and pepper to taste.\nServe with crusty bread and a dollop of sour cream (optional) ", 45 , R.drawable.easy_vegetable_soup );
        insertDish(db,"Mushrooms\nEggs\nChicken\nPepper " ," Easy Egg Drop Soup ", " Beat the eggs.Boil the chicken stock in a saucepan.\n Add soy sauce and pepper, stir well. Add the mushrooms. Wait until boiling again.\n Enter the beaten eggs little by little while stirring.Wait about 2 minutes.\n Lift the saucepan, and the soup is ready to be served.\n(this recipe is for 2-3 bowl.)",  10, R.drawable.easy_egg_drop_soup);
        insertDish(db,"Chicken\nBeans\nMushrooms\nEggs\nSalt " , " Chicken Mushroom Soup", " 1. Heat the chicken stock.2.\n Add the vegetables and boil for 10 minutes.3. Pour in the eggs slowly stirring all the time.4.\n Add soya sauce, salt and pepper.5. Serve hot." ,  20, R.drawable.chicken_mushroom_soup);
        insertDish(db,"Tomatoes\nOnions\nButter\nGarlic\nSausages\nHerbs " , "Sausage Hot Pot " , " Fry the onion in some oil in a saucepan.\nThen add the chopped tomatoes and stir.\nMeanwhile cook either the sausages or the bacon under the grill.\nAdd the mixed veg and cooked potato if using.\nStir and add the butter beans.Crush the garlic and stir in.\nOnce the meat has cooked slice into small pieces and stir in.\nThen add the herbs to taste.\nThis recipe makes enough for two and is good served with bread. " , 25, R.drawable.sausage_hot_pot);
        insertDish(db,"Carrots\nWater\nHerbs " ," Carrot Soup  " , "Peel carrot and chop of top and bottom, slice into 3 chunks roughly.\n Do this for all the carrots. Throw them in a pot, add water,\n ensuring it covers the carrots and a bit more. Add 1 stock cube for every pint of water roughly. Add any herbs, mixed herbs is the easiest. Boil for about 20mins, leave to cool for 10mins and blend.\n Store it in plastic bags or tubs in fridge or freezer once cool and you have soup for ages. ",  25,R.drawable.carrot_soup);
        insertDish(db,"Rice\nSalt\nGarlic\nOnions\nFlour\nOil " , " Rice Tikkis " , " In a bowl mix everthing except oil.Shape into small patties.\nIn a pan add some oil and shallow fry.\nServe with some green chutney." ,  20  , R.drawable.rice_tikkis );
        insertDish(db,"Cucumber\nCheese\nOnions\nPepper\nOil\nTomatoes " , " Greek Salad " ,  " Wash and chop all the vegetables.\nMix in a big bowl.Drizzle some oil on the mixture.\nCrumble up feta cheese over the salad.Mix together..Et voila!\nTips: you can use flavoured olive oil if you want. " ,  20  , R.drawable.greek_salad);






    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int y , int k){}
}
